name: playtogether
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  awesome_extensions: ^2.0.16
  cloud_firestore: ^5.1.0
  envied: ^0.5.4+1
  file_picker: ^8.0.6
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_riverpod: ^2.5.1
  flutter_webrtc: ^0.11.5
  freezed_annotation: ^2.4.4
  google_sign_in_all_platforms:
    git:
      url: https://github.com/DataBPaidiatriko/google_sign_in_all_platforms
      path: google_sign_in_all_platforms
  json_annotation: ^4.9.0
  media_kit: ^1.0.2
  media_kit_libs_video: ^1.0.4
  media_kit_video: ^1.1.6
  riverpod_annotation: ^2.3.5
  window_manager: ^0.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  envied_generator: ^0.5.4+1

dependency_overrides:
  google_sign_in_all_platforms_mobile:
    git:
      url: https://github.com/DataBPaidiatriko/google_sign_in_all_platforms
      path: google_sign_in_all_platforms_mobile

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/icon/

flutter_assets:
  assets_path: assets/
  output_path: lib/
  filename: assets.dart
  field_prefix:
