name: playtogether
description: "A simple shared media player for all your favorite platforms (powered by Flutter)."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  collection: ^1.19.1
  fast_file_picker: ^0.4.8
  flex_color_scheme: ^8.2.0
  file_selector: ^1.1.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7
  supabase_flutter: ^2.12.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  inno_bundle: ^0.11.2

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/subfont.ttf

inno_bundle:
  id: a05680d0-e422-11f0-af00-4b68febb008b
  publisher: Shubham Singh
  languages:
    - english
