// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `pt_user.dart` with the code generated by Freezed
part 'pt_user.freezed.dart';
// optional: Since our PTUser class is serializable, we must add this line.
// But if PTUser was not serializable, we could skip it.
part 'pt_user.g.dart';

@freezed
class PTUser with _$PTUser {
  const factory PTUser({
    required String uid,
    required String name,
    required String email,
    required String? photoURL,
  }) = _PTUser;

  factory PTUser.fromJson(Map<String, Object?> json) => _$PTUserFromJson(json);
}
